name: build docker
on: [push]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo 
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    # Build images
    - name: INFO BUILD
      run: echo ${{ github.event.inputs.path }} ${{ github.event.inputs.image }} ${{ github.event.inputs.version }}
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF#refs/heads/})
    - name: build an image
      run: docker build . --file Dockerfile --tag sweet113/utxo-plugin-test:${{steps.vars.outputs.tag}}
    - name: push image
      run: docker push sweet113/utxo-plugin-test:${{steps.vars.outputs.tag}}
    - name: build an image
      if: github.ref == 'refs/heads/master'
      run: docker build . --file Dockerfile --tag sweet113/utxo-plugin-test:latest
    - name: push image
      if: github.ref == 'refs/heads/master'
      run: docker push sweet113/utxo-plugin-test:latest
    - name: Remove dangling images
      if: ${{ always() }}
      run: yes | docker image prune
